apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-app

resources:
- ../../base

patches:
- path: replica-count.yaml
- path: configmap-patch.yaml

images:
- name: REGISTRY/devops-project-backend
  newName: 865189667386.dkr.ecr.us-east-1.amazonaws.com/k8s-devops-project-backend-dev
  newTag: 4f1ea3e2bffabc179a8b41d490b9e5f07dde4626
- name: REGISTRY/devops-project-frontend
  newName: 865189667386.dkr.ecr.us-east-1.amazonaws.com/k8s-devops-project-frontend-dev
  newTag: 4f1ea3e2bffabc179a8b41d490b9e5f07dde4626
