apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-app
  labels:
    app: devops-dashboard
data:
  ENVIRONMENT: "development"
  SERVICE_NAME: "backend-service"
  BACKEND_URL: "http://backend:5000"
  LOG_LEVEL: "INFO"