apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: devops-app
  labels:
    app: backend
    service: backend-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  type: ClusterIP
  sessionAffinity: None